services:

  base:
    env_file: .env
    working_dir: /home/dev/workspace
    build: ./container
    user: dev
    volumes:
      - type: bind
        source: ${PWD}
        target: /home/dev/workspace
    stdin_open: true 
    tty: true
